app:
  name: "PythonSearchApp"
  version: "3.0.0"

search:
  engines:
    google:
      enabled: true
      max_pages: 3
    duckduckgo:
      enabled: true
      max_pages: 3
  delays:
    google:
      page_load_min: 0.1
      page_load_max: 0.3
      scroll_min: 0.0
      scroll_max: 0.1
      search_dwell_min: 0.1
      search_dwell_max: 0.2
    duckduckgo:
      page_load_min: 0.05
      page_load_max: 0.2
      scroll_min: 0.0
      scroll_max: 0.1
      search_dwell_min: 0.05
      search_dwell_max: 0.15
  scraping:
    max_emails_per_site: 3
    max_phones_per_site: 2
    request_delay: 0.1
    timeout: 3
    results_per_term_limit: 1200
    site_timeout: 5
  retry:
    max_attempts: 3
    base_delay: 1.0
    backoff_factor: 2.0
    max_delay: 60.0

performance:
  tracking_enabled: true
  metrics_retention_hours: 24

mode:
  is_test: true
  complete_threshold: 1000

geolocation:
#  reference_cep: "01310-100" # CEP de referência para cálculo de distâncias
  reference_cep: "18015-000"  # CEP de referência para cálculo de distâncias


geographic_discovery:
  enabled: true
  
  # Validação de CEP de capital (DESABILITADO)
  capital_validation:
    enabled: false
    show_suggestions: true
  
  # APIs de descoberta (100% dinâmico)
  apis:
    viacep:
      enabled: true
      url: "https://viacep.com.br/ws"
    ibge:
      enabled: true
      url: "https://servicodados.ibge.gov.br/api/v1/localidades"
    nominatim:
      enabled: true
      url: "https://nominatim.openstreetmap.org"

  # Rate limiting
  request_delay_seconds: 1.0
  max_retries: 3
  
  # Perfis de descoberta baseados na localização
  profiles:
    metropolitan:
      radius_km: 50
      min_city_population: 500000
      target_large_cities: 10
      exclude_rural_areas: true
      focus_metropolitan_area: true
    rural:
      radius_km: 20
      min_city_population: 10000
      target_large_cities: 10
      exclude_rural_areas: false
      focus_metropolitan_area: false
  
  # Detecção automática de perfil baseada no CEP
  auto_profile_detection:
    enabled: true
    # CEPs de regiões metropolitanas (primeiros 5 dígitos)
    metropolitan_cep_prefixes:
      - "01"    # São Paulo - SP (centro)
      - "02"    # São Paulo - SP (zona norte)
      - "03"    # São Paulo - SP (zona leste)
      - "04"    # São Paulo - SP (zona sul)
      - "05"    # São Paulo - SP (zona oeste)
      - "08"    # São Paulo - SP (região metropolitana)
      - "20"    # Rio de Janeiro - RJ (centro/zona sul)
      - "21"    # Rio de Janeiro - RJ (zona norte)
      - "22"    # Rio de Janeiro - RJ (barra/recreio)
      - "23"    # Rio de Janeiro - RJ (zona oeste)
      - "24"    # Niterói/São Gonçalo - RJ
      - "30"    # Belo Horizonte - MG (centro)
      - "31"    # Belo Horizonte - MG (região metropolitana)
      - "40"    # Salvador - BA (centro)
      - "41"    # Salvador - BA (região metropolitana)
      - "50"    # Recife - PE (centro)
      - "51"    # Recife - PE (região metropolitana)
      - "52"    # Recife - PE (região metropolitana)
      - "60"    # Fortaleza - CE (centro)
      - "61"    # Fortaleza - CE (região metropolitana)
      - "70"    # Brasília - DF
      - "71"    # Brasília - DF
      - "72"    # Brasília - DF
      - "73"    # Brasília - DF
      - "80"    # Curitiba - PR (centro)
      - "81"    # Curitiba - PR (região metropolitana)
      - "82"    # Curitiba - PR (região metropolitana)
      - "90"    # Porto Alegre - RS (centro)
      - "91"    # Porto Alegre - RS (região metropolitana)
      - "92"    # Porto Alegre - RS (região metropolitana)
      - "93"    # Porto Alegre - RS (região metropolitana)
      - "94"    # Porto Alegre - RS (região metropolitana)
      - "95"    # Porto Alegre - RS (região metropolitana)
      - "96"    # Porto Alegre - RS (região metropolitana)