app:
  name: "PythonSearchApp"
  version: "3.0.0"

search:
  engines:
    google:
      enabled: true
      max_pages: 3
    duckduckgo:
      enabled: true
      max_pages: 3

scraping:
  max_emails_per_site: 3
  max_phones_per_site: 2
  request_delay: 0.1
  timeout: 3
  results_per_term_limit: 1200
  site_timeout: 5

retry:
  max_attempts: 3
  base_delay: 1.0
  backoff_factor: 2.0
  max_delay: 60.0

performance:
  tracking_enabled: true
  metrics_retention_hours: 24

delays:
  # Delays otimizados para performance máxima
  google:
    page_load_min: 0.1
    page_load_max: 0.3
    scroll_min: 0.0
    scroll_max: 0.1
    search_dwell_min: 0.1
    search_dwell_max: 0.2
  
  # DuckDuckGo - performance extrema
  duckduckgo:
    page_load_min: 0.05
    page_load_max: 0.2
    scroll_min: 0.0
    scroll_max: 0.1
    search_dwell_min: 0.05
    search_dwell_max: 0.15

mode:
  is_test: true
  complete_threshold: 1000

geolocation:
  reference_cep: "01310-100"  # CEP de referência para cálculo de distâncias